per_listener_settings false
listener 1883 0.0.0.0
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
