allow_anonymous false

listener 1883 0.0.0.0

listener 8883 0.0.0.0
cafile /mosquitto/tls/ca.pem
certfile /mosquitto/tls/server.pem
keyfile /mosquitto/tls/server.key
tls_version tlsv1.2

persistence true
persistence_location /mosquitto/data/

global_plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
